#!/usr/bin/env node
// Build script: encrypts the answer list so the daily word never appears in
// plaintext in the shipped source. Each word is XOR'd with a SHA-256-derived
// key that is unique to its index. The runtime decrypts only today's entry.
//
// Run: node scripts/build-words.js
// Output: js/encrypted-words.js

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ANSWERS = [
  "ABOUT","ABOVE","ABUSE","ACTOR","ACUTE","ADMIT","ADOPT","ADULT","AFTER","AGAIN",
  "AGENT","AGREE","AHEAD","ALARM","ALBUM","ALERT","ALIKE","ALIVE","ALLOW","ALONE",
  "ALONG","ALTER","AMONG","ANGER","ANGLE","ANGRY","APART","APPLE","APPLY","ARENA",
  "ARGUE","ARISE","ARRAY","ASIDE","ASSET","AVOID","AWAKE","AWARD","AWARE","BADLY",
  "BAKER","BASIC","BEACH","BEGAN","BEGIN","BEGUN","BEING","BELOW","BENCH","BIRTH",
  "BLACK","BLAME","BLIND","BLOCK","BLOOD","BOARD","BOAST","BOOST","BOOTH","BOUND",
  "BRAIN","BRAND","BREAD","BREAK","BREED","BRIEF","BRING","BROAD","BROKE","BROWN",
  "BUILD","BUILT","BUYER","CABLE","CARRY","CATCH","CAUSE","CHAIN","CHAIR","CHART",
  "CHASE","CHEAP","CHECK","CHEST","CHIEF","CHILD","CHOSE","CIVIL","CLAIM","CLASS",
  "CLEAN","CLEAR","CLICK","CLOCK","CLOSE","COACH","COAST","COULD","COUNT","COURT",
  "COVER","CRAFT","CRASH","CREAM","CRIME","CROSS","CROWD","CROWN","CURVE","CYCLE",
  "DAILY","DANCE","DEALT","DEATH","DEBUT","DELAY","DEPTH","DOING","DOUBT","DOZEN",
  "DRAFT","DRAMA","DRAWN","DREAM","DRESS","DRILL","DRINK","DRIVE","DROVE","DYING",
  "EAGER","EARLY","EARTH","EIGHT","ELITE","EMPTY","ENEMY","ENJOY","ENTER","ENTRY",
  "EQUAL","ERROR","EVENT","EVERY","EXACT","EXIST","EXTRA","FAITH","FALSE","FAULT",
  "FIBRE","FIELD","FIFTH","FIFTY","FIGHT","FINAL","FIRST","FIXED","FLASH","FLEET",
  "FLOOR","FLUID","FOCUS","FORCE","FORTH","FORTY","FORUM","FOUND","FRAME","FRESH",
  "FRONT","FROST","FRUIT","FULLY","FUNNY","GIANT","GIVEN","GLASS","GLOBE","GOING",
  "GRACE","GRADE","GRAND","GRANT","GRASS","GREAT","GREEN","GROSS","GROUP","GROWN",
  "GUARD","GUESS","GUEST","GUIDE","HAPPY","HEART","HEAVY","HORSE","HOTEL","HOUSE",
  "HUMAN","IDEAL","IMAGE","INDEX","INNER","INPUT","ISSUE","JOINT","JUDGE","KNOWN",
  "LABEL","LARGE","LASER","LATER","LAUGH","LAYER","LEARN","LEASE","LEAST","LEAVE",
  "LEGAL","LEVEL","LIGHT","LIMIT","LOCAL","LOGIC","LOOSE","LOWER","LUCKY","LUNCH",
  "MAGIC","MAJOR","MAKER","MATCH","MAYBE","MAYOR","MEANT","MEDIA","METAL","MIGHT",
  "MINOR","MINUS","MIXED","MODEL","MONEY","MONTH","MORAL","MOTOR","MOUNT","MOUSE",
  "MOUTH","MOVIE","MUSIC","NEEDS","NEVER","NEWLY","NIGHT","NOISE","NORTH","NOTED",
  "NOVEL","NURSE","OCCUR","OCEAN","OFFER","OFTEN","ORDER","OTHER","OUGHT","PAINT",
  "PANEL","PAPER","PARTY","PEACE","PHASE","PHONE","PHOTO","PIECE","PILOT","PITCH",
  "PLACE","PLAIN","PLANE","PLANT","PLATE","POINT","POUND","POWER","PRESS","PRICE",
  "PRIDE","PRIME","PRINT","PRIOR","PRIZE","PROOF","PROUD","PROVE","QUEEN","QUICK",
  "QUIET","QUITE","RADIO","RAISE","RANGE","RAPID","RATIO","REACH","READY","REFER",
  "RIGHT","RIVAL","RIVER","ROUGH","ROUND","ROUTE","ROYAL","RURAL","SCALE","SCENE",
  "SCOPE","SCORE","SENSE","SERVE","SEVEN","SHALL","SHAPE","SHARE","SHARP","SHEET",
  "SHELF","SHELL","SHIFT","SHIRT","SHOCK","SHOOT","SHORT","SHOWN","SIGHT","SINCE",
  "SIXTH","SIXTY","SIZED","SKILL","SLEEP","SLIDE","SMALL","SMART","SMILE","SMOKE",
  "SOLID","SOLVE","SORRY","SOUND","SOUTH","SPACE","SPARE","SPEAK","SPEED","SPEND",
  "SPENT","SPLIT","SPOKE","SPORT","STAFF","STAGE","STAKE","STAND","START","STATE",
  "STEAM","STEEL","STICK","STILL","STOCK","STONE","STOOD","STORE","STORM","STORY",
  "STRIP","STUCK","STUDY","STUFF","STYLE","SUGAR","SUITE","SUPER","SWEET","TABLE",
  "TAKEN","TASTE","TEACH","TEETH","THANK","THEFT","THEIR","THEME","THERE","THESE",
  "THICK","THING","THINK","THIRD","THOSE","THREE","THREW","THROW","TIGHT","TIMES",
  "TIRED","TITLE","TODAY","TOPIC","TOTAL","TOUCH","TOUGH","TOWER","TRACK","TRADE",
  "TRAIN","TREAT","TREND","TRIAL","TRIED","TRIES","TRUCK","TRULY","TRUST","TRUTH",
  "TWICE","UNDER","UNION","UNITY","UNTIL","UPPER","UPSET","URBAN","USAGE","USUAL",
  "VALID","VALUE","VIDEO","VIRUS","VISIT","VITAL","VOICE","WASTE","WATCH","WATER",
  "WHEEL","WHERE","WHICH","WHILE","WHITE","WHOLE","WHOSE","WOMAN","WOMEN","WORLD",
  "WORRY","WORSE","WORST","WORTH","WOULD","WOUND","WRITE","WRONG","WROTE","YIELD",
  "YOUNG","YOUTH"
];

const SECRET = 'ditdah-v1';

function encryptWord(word, index) {
  const key = crypto.createHash('sha256').update(`${SECRET}-${index}`).digest();
  const pt = Buffer.from(word, 'utf8');
  const ct = Buffer.alloc(pt.length);
  for (let i = 0; i < pt.length; i++) ct[i] = pt[i] ^ key[i % key.length];
  return ct.toString('hex');
}

const encrypted = ANSWERS.map(encryptWord);
const out = `// AUTO-GENERATED by scripts/build-words.js — do not edit.
export const ENCRYPTED_WORDS = ${JSON.stringify(encrypted, null, 0)};
export const WORD_SECRET = ${JSON.stringify(SECRET)};
export const EPOCH_DATE = '2024-01-01';
`;

const outPath = path.join(__dirname, '..', 'js', 'encrypted-words.js');
fs.writeFileSync(outPath, out);
console.log(`Wrote ${encrypted.length} encrypted words to ${outPath}`);
